/*
 * CommandDispatcher.h
 *
 *  Created on: Mar 24, 2026
 *      Author: Eric Mintz
 *
 * Copyright (c) 2026, Eric Mintz
 * All Rights Reserved
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or (at your
 * option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program. If not, see <https://www.gnu.org/licenses/>.
 */

#ifndef COMMANDDISPATCHER_H_
#define COMMANDDISPATCHER_H_

#include "InputPinHandler.h"
#include "OutputPinHandler.h"

#include "TaskAction.h"

#include "ConfigurationCommandMessage.h"
#include "CommandInputState.h"
#include "InputValueType.h"
#include "StateTransitionTable.h"
#include "StatusReporter.h"
#include "StatusScope.h"

#include <stdint.h>
#include <PullQueueHT.h>

class CommandDispatcher :
    public TaskAction,
    public StatusReporter {
  PullQueueHT<uint8_t>& input_provider_;
  InputPinHandler& input_handler_;
  OutputPinHandler& output_handler_;
  StateTransitionTable<InputValueType, CommandInputState> transition_table_;

  CommandInputState state_;
  uint8_t command_byte_;
  uint8_t scope_byte_;
  uint8_t pin_byte_;
  uint8_t resistor_config_byte_;

  InputValueType type_of(uint8_t input);

  /**
   * Check a pin's availability in the specified scope and inform
   * the client if it is unavailable. Note that availability means that
   * the pin is available for both `INPUT` and `OUTPUT`.
   *
   * Note that the constructor must populate `transition_table_` to parse
   * the byte sequence generated by `ConfigurationCommandMessage.java`
   * q.v.
   *
   * @param command_scope determines the required availability (e.g. 'INPUT').
   * @return 'true` if the pin is available for the specified use,
   *         `false` otherwise. Note that `false` does not imply that the
   *         pin is in use because it could be off-line.
   */
  bool check_availability(StatusScope command_scope);

  /**
   * Dispatch a command to its specified scope for processing.
   */
  void dispatch_command(void);

  /**
   * Dispatch an `INPUT_SCOPE` command to the input handler for processing.
   */
  void dispatch_to_input(void);

  /**
   * Dispatch an `OUTPUT_SCOPE` command to the output handler for processing.
   */
  void dispatch_to_output(void);

  /**
   * Dispatch a `SERVER_SCOPE` command to the server for processing.
   */
  void dispatch_to_server(void);

public:
  /**
   * Constructor
   *
   * @param status_message_queue carries responses for transmission the client
   * @param input_provider provides the input stream
   * @param input_handler processes commands in the `INPUT_SCOPE`
   * @param output_handler processes commands in the `OUTPUT_SCOPE`
   */
  CommandDispatcher(
      PullQueueHT<StatusMessage>& status_message_queue,
      PullQueueHT<uint8_t>& input_provider,
      InputPinHandler& input_handler,
      OutputPinHandler& output_handler);
  virtual ~CommandDispatcher() = default;

  /**
   * Processing loop that reads, assembles, and dispatches commands.
   */
  virtual void run(void) override;
};

#endif /* COMMANDDISPATCHER_H_ */
